# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger
- '*'

pool:
  vImage: 'ubuntu-latest'
  demands:
  - npm

variables:
  buildConfigration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK 5x'
  inputs:
    package: SDK
    version: '5.x'
    
- task: Npm@1
   displayName: 'Run Npm install'
   inputs:
     verbose: false

- script: './node_modules/. bin/node-sass Teilspin.SpaceGame/wwwroot --output Teilspin.SpaceGame/wwwroot'
  displayName: 'Compile Sass assets'
  
- task: gulp@1
  displayName: 'Run gulp tasks'
  
- script: 'echo "$(Build.DefinitionName), #(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'write build info'
  workingDirectory: Teilspin.SpaceGame/wwwroot

- task: DotNetCoreCLI@2
  displayName: 'Build Project - Release'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration Release'
    projects: '**/*.csproj'